a=input("Enter student name:")
b=input("Enter Age:")
c=input("Enter MailId:")
d=input("Enter mobile number:")
print("STUDENTS INFORMATION")
print("Student name:",a)
print("Age:",b)
print("MailId:",c)
print("Mobile number:",d)
